### ISSUE TITLE
iOS text replacement disregards colon-prefixes

### ISSUE THREAD

**Issue by gvoysey** [warpling/Macmoji#20] opened 2016-07-28 18:21 UTC
as i discovered when iCloud sync updated my phone with my laptop text replacements. 

on OSX, you have to type :foo: to get the foo-emoji. 

on iOS, you just need to type foo.  This is not useful -- a NB in the readme would help.

**Comment by warpling** [comment] 2016-07-29 17:24
This is mentioned in the "Known Problems" section 😕 
A great way to help get this bug fixed on iOS 9 (the issue is different on iOS 10) is to file a duplicate radar (it can be short and sweet).

## My radar 27377015:

Area:
Keyboard

Summary:
Many users use custom Keyboard text substitutions to make typing easier; Often these substitutions include symbols, but it seems the word being replaced often isn't the one in the replacement dictionary. See steps to reproduce for more detail.

Steps to Reproduce:
1. Add a new substitution to the Keyboard settings that uses a symbol like colon in the text to be replaced (example: replace ":zzz:" with "Going to bed!" _or_ ":trump:" with "🎃").
2.Try typing just the word "trump" in Notes and observe that a suggestion is given even when the colon is not typed first.

Expected Results:
Substitution suggestions shouldn't be given unless they match the replacement word.

Actual Results:
Substitution suggestions match just the alphanumeric content

Version:
iOS 8.4.1 12H321 (also confirmed on iOS 9.3)

Notes:
This seems to affect iOS but not macOS, additionally iOS 10 seems to have a different problem I will file in a subsequent radar.

**Closed as completed by warpling** 2016-07-29 17:24 UTC

**Comment by gvoysey** [comment] 2016-07-29 18:39
Thanks for the suggestion.   Should've RTFM :sob:

**Comment by warpling** [comment] 2016-07-29 18:41
No worries! :)
